alias ls="ls --color=auto --group-directories-first"
alias lsa="ls -lah"
alias tmux="tmux -2"
alias grep="grep --color=auto --exclude-dir={.git,tags}"
alias gs="git status"
alias gb="git branch"
alias op="nautilus >/dev/null 2>&1"
alias tmuxcopy="xargs tmux set-buffer"
alias jsonify="python3 -m json.tool"
alias httpserver="python3 -m http.server"
